version: "3"
name: "ironos"
services:
  builder:
    stdin_open: true
    tty: true
    build:
      context: .
    command: /bin/sh
    volumes:
      - ./ci:/build/ci:Z
      - ./:/build/source:Z
