make clean
make -j16 lang=EN
rm -rf Objects/src
make -j16 lang=BG
rm -rf Objects/src
make -j16 lang=CS_CZ
rm -rf Objects/src
make -j16 lang=DE
rm -rf Objects/src
make -j16 lang=DK
rm -rf Objects/src
make -j16 lang=ES
rm -rf Objects/src
make -j16 lang=FI
rm -rf Objects/src
make -j16 lang=FR
rm -rf Objects/src
make -j16 lang=HR
rm -rf Objects/src
make -j16 lang=HU
rm -rf Objects/src
make -j16 lang=IT
rm -rf Objects/src
make -j16 lang=LT
rm -rf Objects/src
make -j16 lang=NL
rm -rf Objects/src
make -j16 lang=NO
rm -rf Objects/src
make -j16 lang=PL
rm -rf Objects/src
make -j16 lang=PT
rm -rf Objects/src
make -j16 lang=RU
rm -rf Objects/src
make -j16 lang=SK
rm -rf Objects/src
make -j16 lang=SR
rm -rf Objects/src
make -j16 lang=SV
rm -rf Objects/src
make -j16 lang=TR
rm -rf Objects/src
make -j16 lang=UA
rm -rf Objects/src
