name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: ls
      run: ls
    - name: make
      run: bash /home/runner/work/ts100/ts100/ci/bashALL.sh
