name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: /home/runner/work/ts100/ts100/ci/
    - name: make
      run: ./buildAll.sh
