name: C/C++ CI

on: [pull_request, push]

jobs:
  build_TS80:

    runs-on: ubuntu-latest
    env:
      working-directory: /build
    steps:
    - uses: actions/checkout@v2
      working-directory: ${{env.working-directory}}
    - name: chmod
      run: chmod +x setup.sh && chmod +x workspace/TS100/build.sh
      working-directory: ${{env.working-directory}}
    - name: setup
      run: ./setup.sh
      working-directory: ${{env.working-directory}}  
    - name: build TS80
      run: cd workspace/TS100 && ./build.sh -m TS80
      working-directory: ${{env.working-directory}}
    - name: Archive TS80 artifacts
      uses: actions/upload-artifact@v2
      working-directory: ${{env.working-directory}}
      with:
        name: TS80
        path: workspace/TS100/Hexfile/TS80_*
        if-no-files-found: error
